require('dotenv').config();
const express = require("express");
const App = express();
require("./Config/MongoConfig");
const Introrouter = require("./Routes/Intro");
const TaskRoute = require('./Routes/Task');
const TodoRoute = require('./Routes/Todo');
const LoginRoute = require("./Routes/LoginRoute");
const RegisterRoute = require("./Routes/RegisterRoute");
var cookies = require("cookie-parser");
App.use(express.json());
App.use(cookies());
App.use(express.urlencoded({ extended: true }));
App.set('view engine', 'ejs');
App.use("/", Introrouter);
App.use("/todo", TodoRoute);
App.use("/task", TaskRoute);
App.use("/login", LoginRoute);
App.use("/register", RegisterRoute);
module.exports = App;
